#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import platform
import shlex
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping, Sequence


class WorkspaceError(RuntimeError):
    pass


@dataclass(frozen=True)
class WorkspacePaths:
    business_pack_root: Path
    foundation_root: Path
    install_prefix: Path
    foundation_python_root: Path
    foundation_python: Path
    foundation_python_bin: Path
    foundation_bin: Path
    foundation_lib: Path
    foundation_core_python: Path
    foundation_config: Path
    activate_posix: Path
    activate_powershell: Path


def repository_root() -> Path:
    return Path(__file__).resolve().parents[1]


def resolve_workspace(root: Path | None = None) -> WorkspacePaths:
    business_pack_root = (root or repository_root()).resolve()
    foundation_root = business_pack_root / "work" / "foundation"
    install_prefix = foundation_root / "install"
    foundation_python_root = install_prefix / "python"
    if os.name == "nt":
        foundation_python = foundation_python_root / "Scripts" / "python.exe"
        foundation_python_bin = foundation_python_root / "Scripts"
    else:
        foundation_python = foundation_python_root / "bin" / "python"
        foundation_python_bin = foundation_python_root / "bin"
    return WorkspacePaths(
        business_pack_root=business_pack_root,
        foundation_root=foundation_root,
        install_prefix=install_prefix,
        foundation_python_root=foundation_python_root,
        foundation_python=foundation_python,
        foundation_python_bin=foundation_python_bin,
        foundation_bin=install_prefix / "bin",
        foundation_lib=install_prefix / "lib",
        foundation_core_python=install_prefix / "share" / "hakoniwa" / "python",
        foundation_config=foundation_root / "config" / "cpp_core_config.json",
        activate_posix=foundation_root / "activate",
        activate_powershell=foundation_root / "Activate.ps1",
    )


def _prepend_path(current: str | None, entries: Sequence[Path]) -> str:
    result: list[str] = []
    seen: set[str] = set()
    for value in [*(str(path) for path in entries), *((current or "").split(os.pathsep))]:
        if not value:
            continue
        normalized = os.path.normcase(os.path.normpath(value))
        if normalized in seen:
            continue
        seen.add(normalized)
        result.append(value)
    return os.pathsep.join(result)


def build_environment(
    paths: WorkspacePaths,
    base: Mapping[str, str] | None = None,
) -> dict[str, str]:
    env = dict(os.environ if base is None else base)
    env.pop("PYTHONPATH", None)
    env.pop("PYTHONHOME", None)
    env.update(
        {
            "HAKONIWA_WORKSPACE_ACTIVE": "1",
            "HAKONIWA_WORKSPACE_ROOT": str(paths.business_pack_root),
            "HAKONIWA_HOME": str(paths.install_prefix),
            "HAKO_CONFIG_PATH": str(paths.foundation_config),
            "HAKO_PDU_ENDPOINT_RUNTIME_DIRS": str(paths.foundation_bin),
            "VIRTUAL_ENV": str(paths.foundation_python_root),
            "PYTHONNOUSERSITE": "1",
        }
    )
    env["PATH"] = _prepend_path(
        env.get("PATH"),
        (paths.foundation_python_bin, paths.foundation_bin),
    )
    system = platform.system()
    if system == "Linux":
        env["LD_LIBRARY_PATH"] = _prepend_path(
            env.get("LD_LIBRARY_PATH"),
            (paths.foundation_lib,),
        )
    elif system == "Darwin":
        env["DYLD_LIBRARY_PATH"] = _prepend_path(
            env.get("DYLD_LIBRARY_PATH"),
            (paths.foundation_lib,),
        )
    return env


def _shell_assignment(name: str, value: str) -> str:
    return f"export {name}={shlex.quote(value)}"


def _render_posix_activate(paths: WorkspacePaths) -> str:
    managed = (
        "PATH",
        "PYTHONPATH",
        "PYTHONHOME",
        "PYTHONNOUSERSITE",
        "VIRTUAL_ENV",
        "HAKONIWA_WORKSPACE_ACTIVE",
        "HAKONIWA_WORKSPACE_ROOT",
        "HAKONIWA_HOME",
        "HAKO_CONFIG_PATH",
        "HAKO_PDU_ENDPOINT_RUNTIME_DIRS",
        "LD_LIBRARY_PATH",
        "DYLD_LIBRARY_PATH",
    )
    lines = [
        "# Generated by tools/workspace.py. Source this file; do not execute it.",
        "",
        "if [ \"${HAKONIWA_WORKSPACE_ACTIVE-}\" = \"1\" ]; then",
        "  echo \"Hakoniwa Workspace Environment is already active.\" >&2",
        "  return 0 2>/dev/null || exit 0",
        "fi",
        "",
    ]
    for name in managed:
        lines.extend(
            [
                f"_HAKONIWA_OLD_{name}_SET=${{{name}+x}}",
                f"_HAKONIWA_OLD_{name}=${{{name}-}}",
            ]
        )
    lines.extend(["", "deactivate_hakoniwa() {"])
    for name in managed:
        lines.extend(
            [
                f"  if [ \"${{_HAKONIWA_OLD_{name}_SET-}}\" = x ]; then",
                f"    export {name}=\"${{_HAKONIWA_OLD_{name}}}\"",
                "  else",
                f"    unset {name}",
                "  fi",
                f"  unset _HAKONIWA_OLD_{name}_SET _HAKONIWA_OLD_{name}",
            ]
        )
    lines.extend(
        [
            "  unset -f deactivate_hakoniwa 2>/dev/null || true",
            "}",
            "",
            "unset PYTHONPATH",
            "unset PYTHONHOME",
            _shell_assignment("HAKONIWA_WORKSPACE_ACTIVE", "1"),
            _shell_assignment("HAKONIWA_WORKSPACE_ROOT", str(paths.business_pack_root)),
            _shell_assignment("HAKONIWA_HOME", str(paths.install_prefix)),
            _shell_assignment("HAKO_CONFIG_PATH", str(paths.foundation_config)),
            _shell_assignment("HAKO_PDU_ENDPOINT_RUNTIME_DIRS", str(paths.foundation_bin)),
            _shell_assignment("VIRTUAL_ENV", str(paths.foundation_python_root)),
            _shell_assignment("PYTHONNOUSERSITE", "1"),
            f"export PATH={shlex.quote(str(paths.foundation_python_bin))}:{shlex.quote(str(paths.foundation_bin))}:$PATH",
        ]
    )
    if platform.system() == "Linux":
        lines.extend(_render_posix_optional_path_prepend("LD_LIBRARY_PATH", paths.foundation_lib))
    elif platform.system() == "Darwin":
        lines.extend(_render_posix_optional_path_prepend("DYLD_LIBRARY_PATH", paths.foundation_lib))
    lines.extend(
        [
            "",
            "echo \"Entered Hakoniwa Workspace Environment: $HAKONIWA_WORKSPACE_ROOT\"",
            "echo \"Run 'deactivate_hakoniwa' to restore the previous shell environment.\"",
            "",
        ]
    )
    return "\n".join(lines)


def _render_posix_optional_path_prepend(name: str, value: Path) -> list[str]:
    quoted = shlex.quote(str(value))
    return [
        f'if [ -n "${{{name}-}}" ]; then',
        f'  export {name}={quoted}:"${{{name}}}"',
        "else",
        f"  export {name}={quoted}",
        "fi",
    ]


def _ps_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _render_powershell_activate(paths: WorkspacePaths) -> str:
    managed = (
        "PATH",
        "PYTHONPATH",
        "PYTHONHOME",
        "PYTHONNOUSERSITE",
        "VIRTUAL_ENV",
        "HAKONIWA_WORKSPACE_ACTIVE",
        "HAKONIWA_WORKSPACE_ROOT",
        "HAKONIWA_HOME",
        "HAKO_CONFIG_PATH",
        "HAKO_PDU_ENDPOINT_RUNTIME_DIRS",
    )
    lines = [
        "# Generated by tools/workspace.py. Dot-source this file.",
        "",
        "if ($env:HAKONIWA_WORKSPACE_ACTIVE -eq '1') {",
        "    Write-Host 'Hakoniwa Workspace Environment is already active.'",
        "    return",
        "}",
        "",
        "$global:HAKONIWA_WORKSPACE_SAVED_ENV = @{}",
    ]
    for name in managed:
        lines.append(
            f"$global:HAKONIWA_WORKSPACE_SAVED_ENV[{_ps_quote(name)}] = "
            f"[Environment]::GetEnvironmentVariable({_ps_quote(name)}, 'Process')"
        )
    lines.extend(
        [
            "",
            "function global:Exit-HakoniwaWorkspace {",
            "    foreach ($entry in $global:HAKONIWA_WORKSPACE_SAVED_ENV.GetEnumerator()) {",
            "        if ($null -eq $entry.Value) {",
            "            Remove-Item (\"Env:\\{0}\" -f $entry.Key) -ErrorAction SilentlyContinue",
            "        } else {",
            "            [Environment]::SetEnvironmentVariable($entry.Key, $entry.Value, 'Process')",
            "        }",
            "    }",
            "    Remove-Variable HAKONIWA_WORKSPACE_SAVED_ENV -Scope Global -ErrorAction SilentlyContinue",
            "    Remove-Item Function:\\Exit-HakoniwaWorkspace -ErrorAction SilentlyContinue",
            "}",
            "",
            "Remove-Item Env:\\PYTHONPATH -ErrorAction SilentlyContinue",
            "Remove-Item Env:\\PYTHONHOME -ErrorAction SilentlyContinue",
            f"$env:HAKONIWA_WORKSPACE_ACTIVE = {_ps_quote('1')}",
            f"$env:HAKONIWA_WORKSPACE_ROOT = {_ps_quote(str(paths.business_pack_root))}",
            f"$env:HAKONIWA_HOME = {_ps_quote(str(paths.install_prefix))}",
            f"$env:HAKO_CONFIG_PATH = {_ps_quote(str(paths.foundation_config))}",
            f"$env:HAKO_PDU_ENDPOINT_RUNTIME_DIRS = {_ps_quote(str(paths.foundation_bin))}",
            f"$env:VIRTUAL_ENV = {_ps_quote(str(paths.foundation_python_root))}",
            f"$env:PYTHONNOUSERSITE = {_ps_quote('1')}",
            f"$env:PATH = {_ps_quote(str(paths.foundation_python_bin))} + ';' + {_ps_quote(str(paths.foundation_bin))} + ';' + $env:PATH",
            "",
            "Write-Host \"Entered Hakoniwa Workspace Environment: $env:HAKONIWA_WORKSPACE_ROOT\"",
            "Write-Host \"Run 'Exit-HakoniwaWorkspace' to restore the previous shell environment.\"",
            "",
        ]
    )
    return "\n".join(lines)


def prepare(paths: WorkspacePaths) -> tuple[Path, Path]:
    paths.foundation_root.mkdir(parents=True, exist_ok=True)
    paths.activate_posix.write_text(_render_posix_activate(paths), encoding="utf-8")
    paths.activate_posix.chmod(paths.activate_posix.stat().st_mode | 0o111)
    paths.activate_powershell.write_text(_render_powershell_activate(paths), encoding="utf-8")
    _install_python_bootstrap(paths)
    return paths.activate_posix, paths.activate_powershell


def _foundation_site_package_dirs(
    paths: WorkspacePaths,
    *,
    windows: bool | None = None,
) -> list[Path]:
    use_windows_layout = os.name == "nt" if windows is None else windows
    if use_windows_layout:
        candidate = paths.foundation_python_root / "Lib" / "site-packages"
        return [candidate] if candidate.is_dir() else []
    return sorted(
        path
        for path in (paths.foundation_python_root / "lib").glob("python*/site-packages")
        if path.is_dir()
    )


def _install_python_bootstrap(paths: WorkspacePaths) -> list[Path]:
    bootstrap_source = paths.business_pack_root / "foundation" / "python"
    bootstrap_module = bootstrap_source / "hakoniwa_workspace_bootstrap.py"
    if not bootstrap_module.is_file():
        raise WorkspaceError(f"Workspace Python bootstrap is missing: {bootstrap_module}")
    installed: list[Path] = []
    content = f"{bootstrap_source}\nimport hakoniwa_workspace_bootstrap\n"
    for site_packages in _foundation_site_package_dirs(paths):
        pth_path = site_packages / "hakoniwa_workspace_bootstrap.pth"
        pth_path.write_text(content, encoding="utf-8")
        installed.append(pth_path)
    return installed


def _python_bootstrap_paths(paths: WorkspacePaths) -> list[Path]:
    return [
        site_packages / "hakoniwa_workspace_bootstrap.pth"
        for site_packages in _foundation_site_package_dirs(paths)
    ]


def runtime_snapshot(paths: WorkspacePaths) -> dict[str, object]:
    if not paths.foundation_python.is_file():
        raise WorkspaceError(
            "Foundation Python was not found. Build the Foundation first: "
            f"{paths.foundation_python}"
        )
    script = r"""
import importlib
import json
import sys

modules = {}
errors = {}
for name in ("hakopy", "hakoniwa_pdu", "hakoniwa_pdu_endpoint"):
    try:
        module = importlib.import_module(name)
        modules[name] = {
            "file": getattr(module, "__file__", None),
            "search_locations": [
                str(path) for path in (getattr(module, "__path__", None) or ())
            ],
        }
    except Exception as exc:
        errors[name] = f"{type(exc).__name__}: {exc}"
print(json.dumps({
    "executable": sys.executable,
    "prefix": sys.prefix,
    "modules": modules,
    "errors": errors,
}, ensure_ascii=False))
"""
    result = subprocess.run(
        [str(paths.foundation_python), "-c", script],
        env=build_environment(paths),
        cwd=paths.business_pack_root,
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise WorkspaceError(result.stderr.strip() or "Foundation Python probe failed")
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise WorkspaceError(f"invalid Foundation Python probe output: {result.stdout}") from exc


def _is_under(value: object, root: Path) -> bool:
    if not isinstance(value, str) or not value:
        return False
    try:
        Path(value).resolve().relative_to(root.resolve())
        return True
    except (OSError, ValueError):
        return False


def _same_lexical_path(value: object, expected: Path) -> bool:
    if not isinstance(value, str) or not value:
        return False
    actual = os.path.normcase(os.path.abspath(os.path.expanduser(value)))
    target = os.path.normcase(os.path.abspath(expected.expanduser()))
    return actual == target


def _module_origins(value: object) -> list[str]:
    if isinstance(value, str):
        return [value]
    if not isinstance(value, Mapping):
        return []
    origins: list[str] = []
    file_origin = value.get("file")
    if isinstance(file_origin, str) and file_origin:
        origins.append(file_origin)
    search_locations = value.get("search_locations")
    if isinstance(search_locations, Sequence) and not isinstance(search_locations, (str, bytes)):
        origins.extend(
            location
            for location in search_locations
            if isinstance(location, str) and location
        )
    return origins


def validate_snapshot(snapshot: Mapping[str, object], paths: WorkspacePaths) -> list[str]:
    errors: list[str] = []
    if not _same_lexical_path(snapshot.get("executable"), paths.foundation_python):
        errors.append(f"sys.executable is outside Foundation Python: {snapshot.get('executable')}")
    if not _is_under(snapshot.get("prefix"), paths.foundation_python_root):
        errors.append(f"sys.prefix is outside Foundation Python: {snapshot.get('prefix')}")
    import_errors = snapshot.get("errors")
    if isinstance(import_errors, Mapping):
        for name, detail in import_errors.items():
            errors.append(f"cannot import {name}: {detail}")
    modules = snapshot.get("modules")
    for name in ("hakopy", "hakoniwa_pdu", "hakoniwa_pdu_endpoint"):
        module_info = modules.get(name) if isinstance(modules, Mapping) else None
        origins = _module_origins(module_info)
        if not origins or not all(_is_under(origin, paths.foundation_root) for origin in origins):
            errors.append(
                f"{name} resolved outside Foundation workspace: {origins or 'missing'}"
            )
    return errors


def doctor(paths: WorkspacePaths) -> int:
    snapshot = runtime_snapshot(paths)
    errors = validate_snapshot(snapshot, paths)
    print(json.dumps(snapshot, ensure_ascii=False, indent=2))
    if errors:
        for error in errors:
            print(f"[NG] {error}", file=sys.stderr)
        return 1
    print("[OK] Foundation Python and Hakoniwa modules are workspace-owned.")
    return 0


def _apply_prompt_environment(shell: str, env: dict[str, str]) -> None:
    name = Path(shell).name.lower()
    if name in {"zsh", "zsh.exe"}:
        env["PROMPT"] = "(hako) %n@%m %1~ %# "
        env["PS1"] = env["PROMPT"]
    elif name in {"bash", "bash.exe"}:
        env["PS1"] = r"(hako) \u@\h \W \$ "
    elif name in {"sh", "sh.exe", "dash", "dash.exe", "ksh", "ksh.exe"}:
        env["PS1"] = "(hako) $ "


def enter(paths: WorkspacePaths) -> int:
    prepare(paths)
    env = build_environment(paths)
    if os.name == "nt":
        shell = (
            shutil.which("pwsh")
            or shutil.which("powershell.exe")
            or shutil.which("cmd.exe")
        )
    else:
        shell = env.get("SHELL") or shutil.which("bash") or shutil.which("sh")
    if shell is None:
        raise WorkspaceError("No interactive shell was found")
    _apply_prompt_environment(shell, env)
    command = _interactive_shell_command(shell)
    env.pop("ENV", None)
    env.pop("BASH_ENV", None)
    print(f"Entering Hakoniwa Workspace Environment: {paths.business_pack_root}")
    print("Use 'exit' to return to the previous environment.")
    return subprocess.run(
        command,
        cwd=paths.business_pack_root,
        env=env,
        check=False,
    ).returncode


def _interactive_shell_command(shell: str) -> list[str]:
    name = Path(shell).name.lower()
    if name in {"pwsh", "pwsh.exe", "powershell", "powershell.exe"}:
        prompt = "function global:prompt { '(hako) PS ' + (Get-Location) + '> ' }"
        return [shell, "-NoLogo", "-NoProfile", "-NoExit", "-Command", prompt]
    if name in {"cmd", "cmd.exe"}:
        return [shell, "/d", "/k", "prompt (hako) $P$G"]
    if name in {"bash", "bash.exe"}:
        return [shell, "--noprofile", "--norc", "-i"]
    if name in {"zsh", "zsh.exe"}:
        return [shell, "-f", "-i"]
    if name in {"fish", "fish.exe"}:
        prompt = "function fish_prompt; echo -n '(hako) '; prompt_pwd; echo -n '> '; end"
        return [shell, "--no-config", "-C", prompt, "-i"]
    if name in {"sh", "sh.exe", "dash", "dash.exe", "ksh", "ksh.exe"}:
        return [shell, "-i"]
    raise WorkspaceError(
        f"Unsupported interactive shell for isolated workspace entry: {shell}"
    )


def run_command(paths: WorkspacePaths, command: Sequence[str]) -> int:
    values = list(command)
    if values and values[0] == "--":
        values = values[1:]
    if not values:
        raise WorkspaceError("run requires a command after --")
    prepare(paths)
    return subprocess.run(
        values,
        cwd=paths.business_pack_root,
        env=build_environment(paths),
        check=False,
    ).returncode


def print_environment(paths: WorkspacePaths, json_output: bool) -> None:
    env = build_environment(paths)
    keys = (
        "HAKONIWA_WORKSPACE_ACTIVE",
        "HAKONIWA_WORKSPACE_ROOT",
        "HAKONIWA_HOME",
        "HAKO_CONFIG_PATH",
        "HAKO_PDU_ENDPOINT_RUNTIME_DIRS",
        "VIRTUAL_ENV",
        "PYTHONNOUSERSITE",
        "PATH",
        "LD_LIBRARY_PATH",
        "DYLD_LIBRARY_PATH",
    )
    data = {key: env[key] for key in keys if key in env}
    data["removed"] = ["PYTHONPATH", "PYTHONHOME"]
    if json_output:
        print(json.dumps(data, ensure_ascii=False, indent=2))
        return
    for key, value in data.items():
        print(f"{key}={value}")


def create_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Enter and validate the isolated Hakoniwa Workspace Environment"
    )
    parser.add_argument(
        "--root",
        default=None,
        help="Business Pack root (default: repository containing this tool)",
    )
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("prepare", help="regenerate compatibility activation scripts")
    sub.add_parser("enter", help="prepare and open the standard (hako) child shell")
    sub.add_parser("doctor", help="verify Python and binding origins")
    env_parser = sub.add_parser("env", help="show the managed environment")
    env_parser.add_argument("--json", action="store_true", dest="json_output")
    run_parser = sub.add_parser("run", help="prepare and run one isolated command")
    run_parser.add_argument("args", nargs=argparse.REMAINDER)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = create_parser().parse_args(argv)
    root = Path(args.root).expanduser() if args.root else None
    paths = resolve_workspace(root)
    try:
        if args.command == "prepare":
            posix, powershell = prepare(paths)
            print(f"POSIX activation    : {posix}")
            print(f"PowerShell activation: {powershell}")
            bootstrap_paths = _python_bootstrap_paths(paths)
            if bootstrap_paths:
                for bootstrap_path in bootstrap_paths:
                    print(f"Python bootstrap    : {bootstrap_path}")
            else:
                print(
                    "Python bootstrap    : Foundation venv not found; "
                    "rerun prepare after Foundation build",
                    file=sys.stderr,
                )
            return 0
        if args.command == "enter":
            return enter(paths)
        if args.command == "doctor":
            return doctor(paths)
        if args.command == "env":
            print_environment(paths, args.json_output)
            return 0
        if args.command == "run":
            return run_command(paths, args.args)
        raise WorkspaceError(f"unsupported command: {args.command}")
    except (WorkspaceError, OSError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())